- packages/components/public/locales/en/categories.json
> fix: change name for locales - ESPP_632

- packages/components/public/locales/fr/api.json
> fix: trads - ESPP_596

- packages/components/src/pages/admin/search/configuration/Attributes.tsx
> revert: add searchBar in attributes page - ESPP_630

- packages/components/assets/scss/_base.scss
> fix: update style auto complete input - ESPP_590

- packages/shared/src/services/api.ts
> fix: messages errors - ESPP_658

- packages/components/src/components/atoms/Alert/Alert.tsx
- packages/components/src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap
- packages/components/src/components/molecules/CustomTable/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/components/src/components/stateful-pages/SettingsAttributes/SettingsAttributes.tsx
- packages/components/src/pages/admin/search/Facets.tsx
- packages/components/src/pages/admin/search/configuration/Attributes.tsx
- packages/shared/src/constants/theme.tsx
> fix: fix-margin-alert-and-table-pagination

- packages/components/assets/scss/_base.scss
> fix: change background on input on page login

- packages/components/src/components/stateful-pages/SettingsAttributes/SettingsAttributes.tsx
- packages/components/src/pages/admin/search/Facets.tsx
> fix: add searchBar for all grids - ESPP_630

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/catalog.json
- packages/components/public/locales/fr/categories.json
- packages/components/public/locales/fr/common.json
- packages/components/public/locales/fr/facet.json
- packages/components/public/locales/fr/settings.json
- packages/components/src/components/atoms/userMenu/UserMenuShow.tsx
- packages/components/src/components/atoms/userMenu/__snapshots__/UserMenu.test.tsx.snap
- packages/components/src/components/molecules/layout/appBar/__snapshots__/AppBar.test.tsx.snap
- packages/components/src/components/molecules/layout/user/__snapshots__/User.test.tsx.snap
> fix: update trads - ESPP_596

- packages/components/src/components/molecules/layout/Sidebar/Sidebar.tsx
- packages/components/src/components/molecules/layout/Sidebar/__snapshots__/Sidebar.test.tsx.snap
> fix: new redirection into page settings when click on logo - ESPP_659

- packages/components/src/components/molecules/layout/Sidebar/Sidebar.tsx
- packages/components/src/components/molecules/layout/Sidebar/__snapshots__/Sidebar.test.tsx.snap
- packages/components/src/pages/GallyApp.tsx
- packages/components/src/pages/Login.tsx
> fix: logo - ESPP_692

- packages/components/src/components/organisms/CustomTable/CustomTable.tsx
> Espp 695 auto placement in top page after paging

- packages/components/src/components/atoms/help/HelpOver.tsx
> fix: new url for api documentation in dev mode

- packages/shared/src/mocks/api.ts
- packages/shared/src/services/hydra.test.ts
- packages/shared/src/services/hydra.ts
- packages/shared/src/types/hydra.ts
> feat: add alias field on gally's hydra fields - ESPP-667

- packages/components/src/pages/admin/merchandize/categories.tsx
- packages/components/src/services/category.ts
> fix: error when catalog change - ESPP_663

- packages/components/src/components/atoms/form/DropDown.styled.tsx
- packages/components/src/components/atoms/rules/Rule.styled.tsx
> fix: update typo - ESPP_660-typo

- packages/components/src/components/organisms/CustomTable/CustomTable.tsx
> fix: bug search on facettes/attributes when no result - ESPP_696

- packages/components/src/components/organisms/PagerTable/PagerTable.tsx
> fix: update typo

- packages/components/assets/scss/_base.scss
> fix: update liseré dans les champs login et mdp

- packages/components/src/components/atoms/form/InputText.tsx
- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
> fix: bug positions ESPP_608

- packages/components/src/pages/admin/merchandize/categories.tsx
> fix: espp-fix-error-in-subCate

- packages/components/__mocks__/@elastic-suite/gally-admin-shared.ts
- packages/components/__mocks__/next/router.ts
- packages/components/src/components/atoms/formatText/FormatText.tsx
- packages/components/src/components/atoms/userMenu/UserMenu.tsx
- packages/components/src/components/atoms/userMenu/UserMenuShow.tsx
- packages/components/src/components/stateful-layout/Layout/Layout.tsx
- packages/components/src/components/stateful-providers/CatalogProvider/CatalogProvider.tsx
- packages/components/src/components/stateful-providers/DataProvider/DataProvider.tsx
- packages/components/src/hocs/withAuth.tsx
- packages/components/src/hooks/useApi.test.ts
- packages/components/src/hooks/useApi.ts
- packages/components/src/hooks/useGraphql.test.ts
- packages/components/src/hooks/useGraphql.ts
- packages/components/src/hooks/useTabs.test.tsx
- packages/components/src/hooks/useTabs.ts
- packages/components/src/hooks/useUser.test.ts
- packages/components/src/hooks/useUser.ts
- packages/components/src/pages/Login.tsx
- packages/components/src/pages/Welcome.tsx
- packages/components/src/pages/admin/Settings.tsx
- packages/components/src/store/user.test.ts
- packages/components/src/store/user.ts
- packages/components/src/utils/tests.tsx
> fix: redirect user when manually clearing the storage

- packages/components/src/pages/admin/boost/Grid.tsx
- packages/components/src/pages/index.ts
> #1191180 Create page grid for boosts 

- packages/components/public/locales/en/boost.json
- packages/components/public/locales/fr/boost.json
- packages/components/src/components/organisms/CustomForm/CustomForm.stories.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.stories.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/shared/src/mocks/static/Boost/1.json
> feat: #1191173 [Form builder] Update actions

- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/shared/src/services/hydra.ts
> feat: #1191173 [Form builder] Initialization data for creation of forms 

- packages/components/src/components/atoms/menu/MenuItem.tsx
- packages/components/src/components/molecules/layout/Menu/Menu.tsx
- packages/shared/src/types/menu.ts
> feat: #1220524 add path in menu for modulable entry

- packages/components/src/components/atoms/form/RequestType.stories.tsx
- packages/components/src/components/atoms/form/RequestType.tsx
- packages/components/src/components/atoms/form/RequestTypeItem.stories.tsx
- packages/components/src/components/atoms/form/RequestTypeItem.styled.tsx
- packages/components/src/components/atoms/form/RequestTypeItem.tsx
- packages/components/src/components/organisms/CustomForm/CustomForm.stories.tsx
- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.stories.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/RequestTypeManager/RequestTypeManager.stories.tsx
- packages/components/src/components/stateful/RequestTypeManager/RequestTypeManager.tsx
- packages/components/src/hooks/useResource.ts
- packages/components/src/services/form.ts
- packages/shared/src/mocks/static/boostWithUseResource.json
- packages/shared/src/mocks/static/boost_limitation_type_options.json
- packages/shared/src/mocks/static/boost_model_options.json
- packages/shared/src/mocks/static/boost_query_text_operator_options.json
- packages/shared/src/mocks/static/boost_request_type_options.json
- packages/shared/src/mocks/static/localized_catalog_group_options.json
- packages/shared/src/mocks/static/requestTypes.json
- packages/shared/src/services/hydra.ts
- packages/shared/src/services/table.ts
- packages/shared/src/types/field.ts
- packages/shared/src/types/hydra.ts
- packages/shared/src/types/requestType.ts
> Feat 1191173 form builder depends

- packages/components/src/hooks/useApiTable.ts
- packages/components/src/services/form.ts
> Refacto form builder

- packages/components/src/components/atoms/metadata/Metadata.tsx
- packages/components/src/components/index.ts
- packages/components/src/components/stateful-pages/SettingsAttributes/SettingsAttributes.tsx
- packages/components/src/components/stateful-providers/MetadataProvider/MetadataProvider.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/components/src/contexts/index.ts
- packages/components/src/contexts/metadata.ts
- packages/components/src/hooks/useDataLoader.ts
- packages/components/src/hooks/useRuleOperators.ts
- packages/components/src/pages/GallyApp.tsx
- packages/components/src/pages/admin/search/configuration/Attributes.tsx
- packages/components/src/utils/TestProvider.tsx
- packages/shared/src/services/rules.ts
- packages/shared/src/services/user.ts
> Feat #1203323 refacto rule component and metadata

- packages/components/src/components/organisms/CustomForm/CustomForm.stories.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.stories.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/shared/src/mocks/static/boostWithUseResource.json
- packages/shared/src/services/hydra.ts
- packages/shared/src/types/customTables.ts
> 1191173 integration rules in form builder

- packages/components/src/components/molecules/layout/Menu/Menu.tsx
- packages/shared/src/services/format.ts
> Feat: #1234593 Verification url for path in menu

- packages/components/src/components/atoms/form/__snapshots__/Dropdown.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/InputText.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/Slider.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/SwitchLabel.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/Textarea.test.tsx.snap
- packages/components/src/components/stateful/Merchandize/__snapshots__/Merchandize.test.tsx.snap
- packages/shared/src/constants/theme.tsx
> Feat: #1234592 Change style labels form

- packages/components/src/components/atoms/form/RequestType.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableDropDownGuesser.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/RequestTypeManager/RequestTypeManager.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/shared/src/services/table.ts
- packages/shared/src/types/field.ts
- packages/shared/src/types/hydra.ts
> Feat: #1234591 Add placeholder for field guesser

- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
> Feat:  #1234590 Add label, required, infoTooltip for rule engine form

- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableDropDownGuesser.tsx
> Feat refacto and fix bug

- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/RequestTypeManager/RequestTypeManager.tsx
- packages/components/src/pages/admin/merchandize/boost/Create.tsx
- packages/components/src/pages/admin/merchandize/boost/Edit.tsx
> Feat 1235190 put categories list in request type from js ld

- packages/components/src/components/atoms/form/Slider.tsx
- packages/shared/src/services/hydra.ts
- packages/shared/src/services/table.ts
- packages/shared/src/types/field.ts
- packages/shared/src/types/hydra.ts
> Feat make default value in form

- packages/components/public/locales/en/resourceForm.json
- packages/components/public/locales/fr/resourceForm.json
- packages/components/src/components/atoms/modals/PopIn.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/pages/admin/merchandize/boost/Create.tsx
- packages/components/src/pages/admin/merchandize/boost/Edit.tsx
- packages/shared/src/services/fetch.ts
> Feat delete boost in edit page

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/form/DatePicker.tsx
- packages/components/src/components/atoms/form/DoubleDatePicker.tsx
- packages/components/src/components/stateful-providers/I18nProvider/I18nProvider.tsx
> Feat 1234594 format and trads double date picker

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/metadata/Metadata.tsx
> feat: #1240402 add trads for medatadas

- packages/components/public/locales/en/rules.json
- packages/components/public/locales/fr/rules.json
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/components/src/pages/admin/merchandize/categories.tsx
> Feat 1236549 gestion of errors rules in form and categories page

- packages/components/src/services/form.ts
> Fix 1234600 depends if value is empty

- packages/shared/src/services/rules.ts
> Fix 1243262 bug when rule was empty on fonction isRuleValid, we had an error

- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
- packages/components/src/services/form.ts
> Feat 1234598 refacto limitations

- packages/components/src/components/atoms/form/DoubleDatePicker.tsx
> Fix 1234983 on error double date picker

- packages/components/public/locales/en/thesaurus.json
- packages/components/public/locales/fr/thesaurus.json
- packages/components/src/pages/admin/search/thesaurus/Create.tsx
- packages/components/src/pages/admin/search/thesaurus/Edit.tsx
- packages/components/src/pages/admin/search/thesaurus/Grid.tsx
- packages/components/src/pages/index.ts
> Feat create pages thesaurus

- packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> Fix 1244237 Gerer probleme de zIndex dans ressourceForm

- packages/components/src/components/atoms/form/InputText.styled.ts
- packages/components/src/components/atoms/rules/CombinationRules.tsx
- packages/components/src/components/atoms/rules/Rule.styled.tsx
- packages/components/src/components/atoms/rules/Rule.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/components/src/pages/admin/merchandize/categories.tsx
> Feat 1244235 Agrandir rule engine dans les form

- packages/components/public/locales/en/common.json
- packages/components/public/locales/en/rules.json
- packages/components/public/locales/fr/common.json
- packages/components/public/locales/fr/rules.json
- packages/components/src/components/atoms/form/RequestTypeItem.tsx
- packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/RulesManager/RulesManager.tsx
- packages/shared/src/services/form.ts
- packages/shared/src/types/textFieldTags.ts
> Feat 1244263 Créer fonction isRequestTypeValid

- packages/components/src/components/stateful/ProductsContainer/ProductsContainer.tsx
- packages/components/src/pages/admin/merchandize/categories.tsx
> fix: #1244380 message erreur dans la page categories

- packages/components/public/locales/en/api.json
- packages/components/public/locales/en/boost.json
- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/api.json
- packages/components/public/locales/fr/boost.json
- packages/components/public/locales/fr/common.json
- packages/components/public/locales/fr/resourceForm.json
- packages/components/src/components/atoms/form/RequestTypeItem.tsx
- packages/components/src/components/molecules/Filters/Filters.tsx
- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> fix: #1242220 tracuctions

- packages/components/src/components/atoms/noAttributes/NoAttributes.tsx
- packages/components/src/components/atoms/noAttributes/__snapshots__/NoAttributes.test.tsx.snap
- packages/components/src/components/stateful-pages/Grid/Grid.tsx
> fix: #125897 height in <a href> in button

- packages/components/package.json
- yarn.lock
> Fix storybook

- packages/components/src/components/atoms/form/TextFieldTags.tsx
> fix: gestion of key when multiple same tags in TextFieldTags

- packages/components/src/components/atoms/form/InputText.styled.ts
> fix: #1246644 make width auto for inputs in rules

- packages/components/src/components/atoms/form/RequestTypeItem.tsx
> Fix 1246638 reset limitations when change apply to all

- packages/components/public/locales/en/boost.json
- packages/components/public/locales/fr/boost.json
- packages/components/src/components/atoms/form/RequestType.tsx
- packages/components/src/components/atoms/form/RequestTypeItem.tsx
- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- packages/components/src/components/stateful/FieldGuesser/FormFieldGuesser.tsx
- packages/components/src/components/stateful/RequestTypeManager/RequestTypeManager.tsx
- packages/components/src/hooks/useApi.ts
- packages/components/src/services/form.ts
- packages/shared/src/services/form.ts
> Fix 1246196 messages error for request type

- packages/components/src/components/atoms/form/TextFieldTags.tsx
> Feat 1246727 when lost focus in text field tads add automaticaly tags

- packages/components/src/components/atoms/rules/Rule.tsx
> Fix 1246725 error when change attributs

- packages/components/src/components/atoms/form/TextFieldTags.tsx
> Fix 1250484 text field tags ameliorations style

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/form/DatePicker.stories.tsx
- packages/components/src/components/atoms/form/DatePicker.tsx
- packages/components/src/components/atoms/form/DatePickerError.tsx
- packages/components/src/components/atoms/form/DoubleDatePicker.stories.tsx
- packages/components/src/components/atoms/form/DoubleDatePicker.tsx
- packages/components/src/components/atoms/form/DoubleDatePickerError.tsx
- packages/components/src/components/stateful-providers/I18nProvider/I18nProvider.tsx
- packages/components/src/services/form.ts
> feat: #1246648 update format of return value on DatePicker to match ISO

- packages/components/src/components/atoms/ReadOnlyTable/MatchTable.stories.tsx
- packages/components/src/components/atoms/ReadOnlyTable/ReadOnlyTable.stories.tsx
- packages/components/src/components/atoms/ReadOnlyTable/ReadOnlyTable.styled.tsx
- packages/components/src/components/atoms/ReadOnlyTable/ReadOnlyTable.tsx
- yarn.lock
> feat: #1244769 ReadOnlyTable and Matches Table Components

- packages/components/package.json
- packages/components/public/locales/en/resourceExplain.json
- packages/components/public/locales/fr/resourceExplain.json
- packages/components/src/components/atoms/modals/PopIn.stories.tsx
- packages/components/src/components/atoms/modals/PopIn.styled.ts
- packages/components/src/components/atoms/modals/PopIn.test.tsx
- packages/components/src/components/atoms/modals/PopIn.tsx
- packages/components/src/components/molecules/Explain/ExplainQueryDetails.stories.tsx
- packages/components/src/components/molecules/Explain/ExplainQueryDetails.tsx
- packages/components/src/components/organisms/CustomTable/CustomTable.stories.tsx
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
- yarn.lock
> Feat 1246177 explain query details

- .github/workflows/ci.yml
- .github/workflows/qa.yml
> Replace on workflow files 1.0.x branch by a pattern

- packages/components/src/hooks/useApi.ts
- packages/components/src/hooks/useDataLoader.ts
- packages/components/src/hooks/useGraphql.ts
- packages/components/src/hooks/useLog.ts
> fix: #1200553 Expired Token stack message

- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
- packages/components/src/components/organisms/CustomTable/CustomTable.styled.tsx
- packages/components/src/components/organisms/CustomTable/__snapshots__/CustomTable.test.tsx.snap
- packages/components/src/components/stateful/FieldGuesser/ReadableFieldGuesser.tsx
- packages/components/src/components/stateful/TopProductsTable/__snapshots__/TopProductsTable.test.tsx.snap
- packages/components/src/hooks/useOptions.ts
> Boost fixes

- packages/components/src/components/atoms/form/DropDown.tsx
- packages/components/src/components/stateful/TableGuesser/TableGuesser.tsx
- packages/components/src/pages/admin/search/thesaurus/Grid.tsx
> Thesaurus fixes after TNR

- packages/shared/src/constants/graphql.ts
- packages/shared/src/services/category.test.ts
- packages/shared/src/services/category.ts
- packages/shared/src/services/format.test.ts
- packages/shared/src/services/format.ts
- packages/shared/src/types/categories.ts
- packages/shared/src/types/documents.ts
- packages/shared/src/types/graphql.ts
> Feat 1243475 autocomplete

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/api.json
- packages/components/src/components/molecules/CustomTable/StickyBar/StickyBar.tsx
- packages/components/src/components/molecules/CustomTable/StickyBar/__snapshots__/StickyBar.test.tsx.snap
- packages/components/src/components/molecules/layout/twoColsLayout/TwoColsLayout.tsx
- packages/components/src/components/molecules/layout/twoColsLayout/__snapshots__/TwoColsLayout.test.tsx.snap
- packages/components/src/components/stateful/ProductsContainer/ProductsContainer.tsx
- packages/components/src/components/stateful/ProductsTopAndBottom/ProductsTopAndBottom.tsx
- packages/components/src/components/stateful/TopAndBottomTable/BottomTable.tsx
- packages/components/src/components/stateful/TopAndBottomTable/TopTable.tsx
- packages/components/src/hooks/useCatalogs.ts
- packages/components/src/pages/admin/merchandize/categories.tsx
- packages/shared/src/constants/graphql.ts
- packages/shared/src/services/rules.test.ts
- packages/shared/src/services/rules.ts
> Fixes after TNR

- packages/components/public/locales/en/resourceTable.json
> fix: #1265834 'thesaurus.none.btn' translation

- packages/shared/src/constants/graphql.ts
- packages/shared/src/types/documents.ts
- packages/shared/src/types/extraBundle.ts
> feat: add getVectorSearchDocumentsQuery and extraBundles constants

- packages/components/src/components/atoms/form/DoubleDatePicker.tsx
- packages/components/src/components/atoms/form/Expansion.tsx
- packages/components/src/components/atoms/form/FormControl.tsx
- packages/components/src/components/atoms/form/InputText.styled.ts
- packages/components/src/components/atoms/form/RequestTypeItem.styled.tsx
- packages/components/src/components/atoms/form/Slider.tsx
- packages/components/src/components/atoms/form/Synonym.tsx
- packages/components/src/components/atoms/form/TextFieldTags.tsx
- packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
- packages/components/src/components/atoms/form/__snapshots__/Dropdown.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/Expansion.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/InputText.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/Slider.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/Synonym.test.tsx.snap
- packages/components/src/components/atoms/form/__snapshots__/TreeSelector.test.tsx.snap
- packages/components/src/components/organisms/CustomTable/__snapshots__/CustomTable.test.tsx.snap
- packages/components/src/components/stateful-pages/SettingsAttributes/SettingsAttributes.tsx
- packages/components/src/components/stateful/Merchandize/SearchBar/__snapshots__/Search.test.tsx.snap
- packages/components/src/components/stateful/Merchandize/__snapshots__/Merchandize.test.tsx.snap
> [Design] fix: issue when label is longer than html field

- packages/components/public/locales/fr/vectorSearch.json
- packages/components/src/components/atoms/metadata/Metadata.tsx
- packages/components/src/pages/admin/search/Vector.tsx
- packages/components/src/pages/index.ts
- packages/shared/src/constants/graphql.ts
- packages/shared/src/types/documents.ts
- packages/shared/src/types/extraBundle.ts
> Feat gally llm

- packages/components/src/components/atoms/score/Score.tsx
- packages/components/src/components/stateful/FieldGuesser/ReadableFieldGuesser.tsx
- packages/shared/src/constants/customTable.ts
- packages/shared/src/services/format.test.ts
- packages/shared/src/services/format.ts
> fix: #1273537 Score rounded at 4 digits after comas

- packages/components/src/components/stateful-providers/RuleOptionsProvider/RuleOptionsProvider.tsx
> fix: #1265415 add pagination to source_fields_options request

- packages/components/src/components/atoms/boost/Boost.tsx
- packages/components/src/components/organisms/PreviewBoostingTable/PreviewBoostingTable.tsx
- packages/shared/src/types/customTables.ts
- packages/shared/src/types/preview.ts
> feat: add arrow boostInfo score component for the preview of the boost

- packages/shared/src/constants/graphql.ts
Add description in product request
Change type a documents request to be able to override value in vector context
> fix: vector search #1241202 Fix collection type

- packages/components/__mocks__/@elastic-suite/gally-admin-shared.ts
- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/hooks/useApi.ts
- packages/components/src/hooks/useResource.ts
- packages/components/src/pages/admin/search/Vector.tsx
- packages/shared/src/services/api.test.ts
- packages/shared/src/services/api.ts
- packages/shared/src/types/api.ts
> [Performance] #1284197 Improve render of InputTexts on auto save grids

- packages/components/src/components/atoms/form/Checkbox.tsx
- packages/components/src/components/atoms/form/DropDown.tsx
> fix(#1285907): [Boost] UX Field Localized Catalog

- packages/components/src/components/atoms/form/DropDown.tsx
> [Boost] #1255766 Selection placeholder Dropdown

- packages/components/src/components/stateful/ProductsContainer/ProductsContainer.tsx
> fix(#1279113): [Category] product positions not correctly saved

- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/positionEffect/PositionEffect.stories.tsx
- packages/components/src/components/atoms/positionEffect/PositionEffect.test.tsx
- packages/components/src/components/atoms/positionEffect/PositionEffect.tsx
- packages/components/src/components/atoms/positionEffect/__snapshots__/PositionEffect.test.tsx.snap
- packages/components/src/components/organisms/PreviewBoostingTable/PreviewBoostingTable.tsx
- packages/components/src/components/stateful/FieldGuesser/ReadableFieldGuesser.tsx
- packages/shared/src/types/customTables.ts
> [Boost] #1282987 Add position effect column on boost preview

- packages/components/src/components/atoms/form/Switch.tsx
- packages/components/src/components/atoms/form/__snapshots__/SwitchLabel.test.tsx.snap
- packages/components/src/components/organisms/CustomForm/CustomForm.styled.tsx
- packages/components/src/components/organisms/CustomTable/__snapshots__/CustomTable.test.tsx.snap
- packages/components/src/components/stateful/Merchandize/__snapshots__/Merchandize.test.tsx.snap
> [Boost] #1255747 Gap between enable and name

- packages/components/public/locales/fr/explain.json
- packages/components/src/components/molecules/Explain/ExplainDetails.styled.tsx
- packages/components/src/components/molecules/Explain/ExplainDetails.tsx
> [Explain] Add indexed content

- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/hooks/useApi.ts
…m back, because back can update several values after one change
> [Grid] #1295483 After an edit from a grid make a GET to get values from back

- packages/shared/src/services/category.ts
- packages/shared/src/types/products.ts
> feat(#1275390): add AUTOCOMPLETE key to ProductRequestType enum

- packages/components/src/components/organisms/CustomTable/CustomTableRow/DraggableRow.tsx
- packages/components/src/components/organisms/CustomTable/CustomTableRow/NonDraggableRow.tsx
- packages/components/src/components/organisms/PreviewBoostingTable/PreviewBoostingTable.tsx
> fix(#1297180): [Boost Preview] Wrong Media url

- packages/components/public/locales/en/boost.json
- packages/components/public/locales/fr/boost.json
- packages/components/src/components/atoms/form/SearchBar.tsx
- packages/components/src/components/molecules/FiltersPreviewBoostingTabs/FiltersPreviewBoostingTab.tsx
> fix(#1298299): [Boost Preview] Submit with "Enter" key does'nt work

- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/hooks/useApi.ts
> fix(#1294900): [Grid] Search field slow

- packages/components/src/components/atoms/rules/Rule.tsx
- packages/shared/src/types/rules.ts
> feat(#1278904): [Source Field] Manage Date attributes

- packages/components/public/locales/en/common.json
- packages/components/public/locales/fr/common.json
- packages/components/src/components/atoms/form/DoubleDatePickerError.test.tsx
- packages/components/src/components/atoms/form/DoubleDatePickerError.tsx
- packages/components/src/components/atoms/form/DropDownError.test.tsx
- packages/components/src/components/atoms/form/DropDownError.tsx
- packages/components/src/components/atoms/form/InputTextError.test.tsx
- packages/components/src/components/atoms/form/InputTextError.tsx
- packages/components/src/components/atoms/form/RangeError.test.tsx
- packages/components/src/components/atoms/form/RangeError.tsx
- packages/components/src/components/molecules/CustomTable/StickyBar/StickyBar.tsx
- packages/components/src/components/molecules/CustomTable/StickyBar/__snapshots__/StickyBar.test.tsx.snap
- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableDropDownGuesser.tsx
- packages/components/src/components/stateful/FieldGuesser/EditableFieldGuesser.tsx
- packages/components/src/components/stateful/TableGuesser/TableGuesser.tsx
- packages/components/src/components/stateful/TableStickyBar/TableStickyBar.tsx
- packages/components/src/hooks/useApi.ts
- packages/components/src/hooks/useFormError.ts
- packages/shared/src/services/table.test.ts
- packages/shared/src/services/table.ts
- packages/shared/src/types/api.ts
- packages/shared/src/types/field.ts
- packages/shared/src/types/hydra.ts
> fix(#1282746): [Grid] Add error validation in grid

- packages/components/public/locales/en/resourceForm.json
- packages/components/public/locales/fr/resourceForm.json
- packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> chore(#1294199): [Form] Update ResourceForm texts

- packages/shared/src/constants/graphql.ts
- packages/shared/src/types/aggregation.ts
- packages/shared/src/types/products.ts
> feat(#1300722): [Source Field] Manage Geopoint Attribute - skateboard

- packages/components/package.json
- yarn.lock
> feat(#1277555): remove dayjs from depandencies

- packages/components/public/locales/en/categories.json
- packages/components/public/locales/fr/categories.json
- packages/components/src/components/stateful/Merchandize/Merchandize.tsx
> feat(#1309381): change label add more spacing

- packages/components/src/hooks/useResource.ts
> fix(#1314409): Error on Boost/Thesaurus creation

- packages/components/public/locales/fr/api.json
> fix(#1317671): no FR translations for 'Use for span queries'

- packages/components/src/components/atoms/form/DropDownWithoutError.tsx
- packages/components/src/components/atoms/form/PreviewGridBoostConfiguration/PreviewGridBoostConfiguration.tsx
- packages/components/src/components/atoms/menu/MenuItem.tsx
- packages/components/src/components/atoms/menu/MenuItemIcon.tsx
- packages/components/src/components/molecules/layout/Sidebar/__snapshots__/Sidebar.test.tsx.snap
- packages/components/src/components/organisms/CustomForm/CustomForm.tsx
- packages/components/src/components/organisms/CustomTable/__snapshots__/CustomTable.test.tsx.snap
> Feat 1304624 tests e2e playwright

- packages/components/src/components/stateful/FieldGuesser/MultipleInput.tsx
> fix(#1330035): multiple input component doesn't initialize default value

- packages/components/public/locales/fr/api.json
- packages/components/src/components/molecules/layout/Menu/Menu.stories.tsx
- packages/components/src/components/molecules/layout/Sidebar/Sidebar.stories.tsx
- packages/components/src/components/molecules/layout/Sidebar/Sidebar.test.tsx
- packages/components/src/components/molecules/layout/Sidebar/__snapshots__/Sidebar.test.tsx.snap
- packages/components/src/pages/admin/analyze/Results.tsx
- packages/components/src/pages/index.ts
- packages/shared/src/mocks/static/menu.json
> [Menu] Rename 'Catalog Structure' to 'Results'

- packages/components/src/components/stateful/FieldGuesser/ReadableFieldGuesser.tsx
> [Grids] Fix error on grids when image and/or stock values are empty

- packages/shared/src/constants/api.ts
- packages/shared/src/services/format.test.ts
- packages/shared/src/services/format.ts
> feat: set default api route prefix to 'api'

- packages/components/src/components/molecules/CustomTable/Pagination/Pagination.tsx
- packages/components/src/components/molecules/CustomTable/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/components/src/components/organisms/PagerTable/PagerTable.tsx
- packages/components/src/components/stateful-pages/ResourceTable/ResourceTable.tsx
- packages/components/src/components/stateful/TableGuesser/TableGuesser.tsx
> feat(#1330810): add pagination data-tests-id

- packages/components/src/components/molecules/Explain/ExplainDetails.tsx
> fix(#1333302): error in explain when price is empty

- packages/components/src/components/molecules/Explain/ExplainDetails.tsx
> fix(#1333302): error in explain when price is null

- packages/components/src/components/atoms/form/PreviewGridBoostConfiguration/PreviewGridBoostConfiguration.tsx
- packages/components/src/components/molecules/FiltersPreviewBoostingTabs/FiltersPreviewBoostingTabs.tsx
- packages/components/src/components/organisms/PreviewBoostingTable/PreviewBoostingTableManager.tsx
> fix(#1335198): boosts are not applied to autocomplete

- packages/components/src/pages/Login.tsx
> fix(#1336097): email format message error is not correct in login page

- packages/components/public/locales/en/boost.json
- packages/components/public/locales/fr/boost.json
- packages/components/src/components/molecules/ProportionalToAttributes/ProportionalToAttributes.tsx
- packages/components/src/components/molecules/ProportionalToAttributes/__snapshots__/ProportionalToAttributes.test.tsx.snap
> feat(#1314737): add tooltip to scale factor in the proportionnalToAttributes component

- packages/components/src/components/atoms/form/PreviewGridBoostConfiguration/PreviewGridBoostConfiguration.tsx
- packages/components/src/components/atoms/form/RequestType.tsx
> Fix(#336118): boost requestype terms and autocomplete

- packages/components/src/components/atoms/form/PreviewGridBoostConfiguration/PreviewGridBoostConfiguration.tsx
- packages/components/src/components/molecules/layout/tabs/CustomTabs.tsx
- packages/components/src/components/organisms/PreviewBoostingTable/PreviewBoostingTableManager.tsx
> [Boost] Fix errors on preview and save process

- package.json
- packages/components/package.json
- packages/components/src/components/atoms/charts/BarChart.stories.tsx
- packages/components/src/components/atoms/charts/BarChart.tsx
- packages/components/src/components/atoms/charts/LineChart.stories.tsx
- packages/components/src/components/atoms/charts/LineChart.tsx
- packages/components/src/components/atoms/charts/PieChart.stories.tsx
- packages/components/src/components/atoms/charts/PieChart.tsx
- packages/components/src/components/atoms/charts/chart.styled.tsx
- packages/components/src/components/atoms/charts/chart.tsx
- yarn.lock
> feat(#1244775): Search terms diagram design system

- packages/components/src/components/organisms/CustomTable/CustomTable.tsx
- packages/components/src/components/organisms/PagerTable/PagerTable.tsx
> feat(#1330810): add dataTestId to manipulate grids

- packages/components/public/locales/fr/searchUsage.json
- packages/components/src/components/atoms/form/Form.tsx
- packages/components/src/components/molecules/ScopeSearchUsage/ScopeSearchUsage.stories.tsx
- packages/components/src/components/molecules/ScopeSearchUsage/ScopeSearchUsage.styled.tsx
- packages/components/src/components/molecules/ScopeSearchUsage/ScopeSearchUsage.test.tsx
- packages/components/src/components/molecules/ScopeSearchUsage/ScopeSearchUsage.tsx
- packages/components/src/components/molecules/ScopeSearchUsage/__snapshots__/ScopeSearchUsage.test.tsx.snap
> [Dashboard] #1244775 - Scope component search usage design system

- packages/components/public/locales/en/searchUsage.json
- packages/components/public/locales/fr/searchUsage.json
- packages/components/src/components/atoms/ReadOnlyTable/ReadOnlyTable.styled.tsx
- packages/components/src/components/atoms/ReadOnlyTable/ReadOnlyTable.tsx
- packages/components/src/components/molecules/SearchTermsTable/SearchTermsTable.stories.tsx
- packages/components/src/components/molecules/SearchTermsTable/SearchTermsTable.styled.ts
- packages/components/src/components/molecules/SearchTermsTable/SearchTermsTable.test.tsx
- packages/components/src/components/molecules/SearchTermsTable/SearchTermsTable.tsx
- packages/components/src/components/molecules/SearchTermsTable/__snapshots__/SearchTermsTable.test.tsx.snap
> [Dashboard] #1244775 - Search terms table design system
